spring:
  application:
    name: scorpio-process
server:
  port: 9527
  servlet:
    context-path: /cloud-native

scorpio-process:
  types:
    - docker
    - k8s
  config:
    docker:
      host: unix://${user.home}/.docker/run/docker.sock
      tls-verify: false
      cert-path: ${user.home}/.docker
#      auth:
#        username: admin
#        password: 123123
#        email: abc@qq.com
#        url: https://index.docker.io/v1/
      http:
        connection-timeout: 10000
        max-connect: 10
        response_timeout: 4500
#      ssl:
#        enabled: true
#        protocol: TLSv1.2
#        verify-hostname: true
#        key-store:
#          path: /home/user/.docker/keyStore.jks
#          password: changeit
#          type: JKS
#        trust-store:
#          path: /home/user/.docker/trustStore.jks
#          password: changeit
#          type: JKS
    k8s:
      master: https://mymaster.com
      disable-autoconfig: false
      api-version: v1
      trust-certificates: true
      kube-config: ~/.kube/config
      connection-timeout: 10000     # ?????0 ?????
      request-timeout: 10000        # ??????????
      retry-limit: 10               # ??????-1 ?????
      retry-interval: 100           # ????????????????
      auth:
        try-service-account: true
        try-kube-config: true
      watch:
        reconnect-interval: 1000    # ????????????
        reconnect-limit: -1         # ????????-1 ?????

